name: C++ with CMake with tests

on: [push, pull_request]

jobs:
  Game:

    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: mkdir bowling/build
      run: mkdir bowling/build
    - name: Compile
      working-directory: bowling/build
      run: |
        sudo apt-get update
        cmake ..
        make
    - name: Run tests
      working-directory: bowling/build
      run: ctest -V
